### ISSUE TITLE
Regression in expect_message between v1.1.0 and v1.2.0

### ISSUE THREAD

**Issue by jozefhajnala** [markvanderloo/tinytest#51] opened 2020-05-07 12:46 UTC
It seems that there is a regression in `expect_message()` as it now only captures the first message produced by the tested call: https://github.com/markvanderloo/tinytest/commit/220c8bfa6e07a2ebf26d5602c608b62b4f70864f#diff-db01a1b7dcaea272eccac3b208c64a64R481. 

As can be seen from this reproducible example:

### With tinytest version 1.1.0 - works as expected (captures both messages):

```bash
docker run --rm -it r-base Rscript -e " \
 download.file('https://cran.r-project.org/src/contrib/Archive/tinytest/tinytest_1.1.0.tar.gz', destfile = 'tinytest_1.1.0.tar.gz')
 install.packages('tinytest_1.1.0.tar.gz', repos = NULL)
 foo <- function() { message('one'); message('two'); 1 };
 tinytest::expect_message(foo(), 'one')
 tinytest::expect_message(foo(), 'two')
"
```
relevant output:
```
----- PASSED      : <-->
 call| tinytest::expect_message(foo(), "one") 
----- PASSED      : <-->
 call| tinytest::expect_message(foo(), "two") 
```

### Whereas with tinytest 1.2.0 (captures only the first message):

```bash
docker run --rm -it r-base Rscript -e " \
 download.file('https://cran.r-project.org/src/contrib/tinytest_1.2.0.tar.gz', destfile = 'tinytest_1.2.0.tar.gz')
 install.packages('tinytest_1.2.0.tar.gz', repos = NULL)
 foo <- function() { message('one'); message('two'); 1 };
 tinytest::expect_message(foo(), 'one')
 tinytest::expect_message(foo(), 'two')
"
```

relevant output:

```
----- PASSED      : <-->
 call| tinytest::expect_message(foo(), "one") 
----- FAILED[xcpt]: <-->
 call| tinytest::expect_message(foo(), "two")
 diff| The message message
 diff| 'one
 diff| '
 diff| does not match pattern 'two' 
```

**Comment by markvanderloo** [comment] 2020-05-07 19:39
Thanks for reporting Jozef,

The old version of `expect_message()` also caught output written to `stdout` which was inaccurate, so now there's a function `expect_stdout`. 

I'll have a look what's the best way to take care of this. tbh this was an effect of the old implementation that was unintended, but I can see its use.

**Comment by jozefhajnala** [comment] 2020-05-07 20:12
> Thanks for reporting Jozef,
> 
> The old version of `expect_message()` also caught output written to `stdout` which was inaccurate, so now there's a function `expect_stdout`.
> 
> I'll have a look what's the best way to take care of this. tbh this was an effect of the old implementation that was unintended, but I can see its use.

Thanks for the quick reply! Indeed the issue is bit more generic because of how `tryCatch()` is used, e.g. 

```r
foo <- function() { warning('zero'); message('one'); 1 };
tinytest::expect_message(foo(), 'one')
```

Will fail, but at least in my understanding and opinion, it should not fail, as the test does not ask anything about warnings, it merely asks whether there is a message that contains `'one'` in it arising as an effect of the call.

**Comment by rfhb** [comment] 2020-05-16 13:51
Hi and thanks for tinytest - 

(a.) a minimally reproducible example of a test that fails since 1.2.0 is, 
```
tinytest::expect_message(
  {
    message("catch_one")
    message("catch_two")
  },
  pattern = "two"
)
```

(b.) happy to try to find a fix and submit  a PR, but can you confirm the expected behaviour is that all messages emitted by the expression `current` in `expect_message(current, pattern, ...)` should be checked against the pattern? This would be in analogy to testthat. 

From a quick glance, this is related to no more using `sink()` in order to separate other sources (cat, print, ...). Perhaps unexpectedly, the message handler as used in `tryCatch()` in the `expect_message` function only checks the first message. Possibly, a restart or some other extension of `tryCatch()` is needed. 

Just to flag that this breaking change in 1.2.0 is breaking testing of some of my packages, with a retraction from CRAN looming if not fixed ...

**Comment by markvanderloo** [comment] 2020-05-16 19:58
Ok, should be fixed in https://github.com/markvanderloo/tinytest/commit/d8ae4004a3daef681b0b7b1e6b586c4480b08f27. 

If you could give it a quick spin I'd be grateful. I need to run rev dep tests and update so more informative `diff` messages are created. Otherwise the main semantics should be ok now. I will push to CRAN asap (tomorrow or early this week-ish if all checks out)

**Comment by rfhb** [comment] 2020-05-17 07:56
Thanks a lot for rapid work! Works well for me. Issue #51 could be closed for me.

**Comment by jozefhajnala** [comment] 2020-05-17 08:56
Thank you, this also fixes my package's R CMD check unit tests failure!
Thanks for the quick fix! Any idea when this could be re-submitted to CRAN?

**Comment by markvanderloo** [comment] 2020-05-17 16:35
I will try to resubmit within 3 days. It will probably take a manual intervention at CRAN because of the short time between 1.2.0 and 1.2.1. If you post the names of your packages that are in trouble because of the regression then I can communicate this to the CRAN team.

**Comment by rfhb** [comment] 2020-05-17 16:56
Thanks again - my package `ctrdata` is affected. CRAN maintainers left me time until 2020-05-30, which should suffice without intervention.

**Comment by jozefhajnala** [comment] 2020-05-17 17:53
Thanks again!
On my end it is `languageserversetup` (https://cran.r-project.org/package=languageserversetup)
Link to check results: https://cran.r-project.org/web/checks/check_results_languageserversetup.html

**Comment by markvanderloo** [comment] 2020-05-17 18:17
Cheers again!

All lights are green: revdeps check OK and `rhub::check_for_cran()` as well.

I just want to re-read and improve the `diff` messages a bit b/c they become a bit more involved with explicit multi-message testing. I will resubmit tomorrow (on the 18th).

**Comment by markvanderloo** [comment] 2020-05-18 12:15
`tinytest 1.2.1` is accepted on CRAN. No manual intervention necessary.

What I advise you to do, is to respond to CRAN, with me in cc, stating that the errors in your package were due to a tinytest regression. Now that tinytest 1.2.1 is on CRAN the errors should disappear in the coming days. You can add that we've been in touch and that we've tested the  solution.

I'm closing the issue now. Thanks again for your contributions!

**Closed by markvanderloo** 2020-05-18 12:15 UTC
